return {
    ignored = {
        Contractors = true, -- whats is this? https://www.openstreetmap.org/node/10570296010
        loading_dock = true, -- not needed
    },
    properties = {
        animal_boarding = {
            ["animal_boarding"] = true,
            ["genus"] = true,
            ["species"] = true,
            ["taxon"] = true,
        },
        animal_shelter = {
            ["animal_shelter"] = true,
            ["animal_shelter:adoption"] = true,
            ["animal_shelter:release"] = true,
            ["animal_shelter:sanctuary"] = true,
            ["genus"] = true,
            ["species"] = true,
            ["taxon"] = true,
        },
        bank = {
            ["atm"] = true,
            ["payment"] = true,
        },
        bar = {
            ["live_music"] = true,
            ["microbrewery"] = true,
            ["real_ale"] = true,
        },
        bench = {
            ["armrest"] = true,
            ["backrest"] = true,
            ["bench:type"] = true,
            ["capacity"] = true,
            ["colour"] = true,
            ["covered"] = true,
            ["inscription"] = true,
            ["length"] = true,
            ["material"] = true,
            ["memorial"] = true,
            ["seats"] = true,
            ["surface"] = true,
            ["two_sided"] = true,
        },
        bicycle_parking = {
            ["access"] = true,
            ["bicycle_parking"] = true,
            ["camera:mount"] = true,
            ["camera:type"] = true,
            ["capacity"] = true,
            ["capacity:cargo_bike"] = true,
            ["covered"] = true,
            ["fee"] = true,
            ["indoor"] = true,
            ["locked"] = true,
            ["supervised"] = true,
            ["surveillance"] = true,
            ["surveillance:type"] = true,
        },
        bus_station = {},
        cafe = {
            ["air_conditioning"] = true,
            ["bakery"] = true,
            ["capacity"] = true,
            ["cuisine"] = true,
            ["diet"] = true,
            ["dog"] = true,
            ["ice_cream"] = true,
            ["indoor_seating"] = true,
            ["internet_access"] = true,
            ["outdoor_seating"] = true,
            ["pastry"] = true,
            ["payment"] = true,
            ["reusable_packaging:offer"] = true,
            ["self_service"] = true,
            ["smoking"] = true,
            ["takeaway"] = true,
            ["television"] = true,
        },
        car_wash = {
            ["automated"] = true,
            ["dog_washing"] = true,
            ["high_pressure_washer"] = true,
            ["payment"] = true,
            ["self_service"] = true,
            ["tank_cleaning_truck"] = true,
            ["truck_wash"] = true,
            ["tunnel"] = true,
            ["vacuum_cleaner"] = true,
            ["vacuum_cleaner:free"] = true,
            ["vacuum_cleaner:self_service"] = true,
        },
        charging_station = {
            ["access"] = true,
            ["authentication"] = true,
            ["bicycle"] = true,
            ["bus"] = true,
            ["capacity"] = true,
            ["charging_station:output"] = true,
            ["electric_bicycle"] = true,
            ["hgv"] = true,
            ["moped"] = true,
            ["motorcar"] = true,
            ["motorcycle"] = true,
            ["payment"] = true,
            ["small_electric_vehicle"] = true,
            ["socket"] = true,
        },
        clinic = {
            ["healthcare:speciality"] = true,
        },
        community_centre = {
            ["community_centre"] = true,
            ["community_centre:for"] = true,
        },
        doctors = {
            ["healthcare:speciality"] = true,
        },
        fast_food = {
            ["capacity"] = true,
            ["cuisine"] = true,
            ["delivery"] = true,
            ["diet:healthy"] = true,
            ["diet:lactose_free"] = true,
            ["diet"] = true,
            ["fast_food"] = true,
            ["outdoor_seating"] = true,
            ["reusable_packaging:offer"] = true,
            ["takeaway"] = true,
        },
        fire_station = {},
        fuel = {
            ["advertising"] = true,
            ["capacity"] = true,
            ["car_wash"] = true,
            ["compressed_air"] = true,
            ["currency"] = true,
            ["fast_food"] = true,
            ["fuel"] = true,
            ["fuel:diesel"] = true,
            ["fuel:HGV_diesel"] = true,
            ["fuel:lpg"] = true,
            ["fuel:octane_92"] = true,
            ["fuel:octane_95"] = true,
            ["fuel:octane_98"] = true,
            ["hgv"] = true,
            ["payment"] = true,
            ["payment:cash"] = true,
            ["sanitary_dump_station"] = true,
            ["shop"] = true,
            ["toilets"] = true,
            ["water_point"] = true,
        },
        grave_yard = {
            ["denomination"] = true,
            ["religion"] = true,
        },
        hospital = {
            ["beds"] = true,
            ["emergency"] = true,
        },
        library = {
            ["access"] = true,
            ["books"] = true,
            ["internet_access"] = true,
            ["internet_access_1"] = true,
        },
        marketplace = {
            ["building"] = true,
        },
        nightclub = {
            ["live_music"] = true,
            ["music"] = true,
        },
        parking = {
            ["access"] = true,
            ["capacity"] = true,
            ["capacity:charging"] = true,
            ["capacity:disabled"] = true,
            ["capacity:parent"] = true,
            ["fee"] = true,
            ["park_ride"] = true,
            ["parking"] = true,
            ["supervised"] = true,
            ["surface"] = true,
        },
        parking_space = {
            ["capacity"] = true,
            ["parking_space"] = true,
        },
        pharmacy = {
            ["dispensing"] = true,
            ["payment"] = true,
            ["recycling"] = true,
        },
        place_of_worship = {
            ["access"] = true,
            ["church:type"] = true,
            ["denomination"] = true,
            ["place_of_worship"] = true,
            ["religion"] = true,
            ["shrine"] = true,
        },
        police = {},
        post_office = {
            ["atm"] = true,
            ["flag:type"] = true,
            ["man_made"] = true,
            ["post_office"] = true,
            ["post_office:id_check"] = true,
            ["post_office:letter_from"] = true,
            ["post_office:oversized_item"] = true,
            ["post_office:packaging"] = true,
            ["post_office:parcel_from"] = true,
            ["post_office:parcel_pickup"] = true,
            ["post_office:parcel_to"] = true,
            ["post_office:post_bank"] = true,
            ["post_office:stamps"] = true,
            ["vending"] = true,
        },
        pub = {
            ["cocktail"] = true,
            ["cuisine"] = true,
            ["dog"] = true,
            ["drink"] = true,
            ["food"] = true,
            ["internet_access"] = true,
            ["live_music"] = true,
            ["microbrewery"] = true,
            ["outdoor_seating"] = true,
            ["real_ale"] = true,
            ["real_cider"] = true,
            ["real_fire"] = true,
            ["real_fire:fuel"] = true,
            ["real_fire:visible"] = true,
            ["smoking"] = true,
        },
        public_bath = {
            ["bath:type"] = true,
            ["fee"] = true,
            ["female"] = true,
            ["location"] = true,
            ["male"] = true,
            ["nudism"] = true,
            ["shower"] = true,
            ["unisex"] = true,
        },
        ranger_station = {},
        recycling = {
            ["capacity"] = true,
            ["location"] = true,
            ["material"] = true,
            ["recycling"] = true,
            ["recycling_type"] = true,
        },
        restaurant = {
            ["air_conditioning"] = true,
            ["bar"] = true,
            ["breakfast"] = true,
            ["capacity"] = true,
            ["changing_table"] = true,
            ["cuisine"] = true,
            ["delivery"] = true,
            ["diet"] = true,
            ["dinner"] = true,
            ["dog"] = true,
            ["internet_access"] = true,
            ["kids_area"] = true,
            ["lunch"] = true,
            ["microbrewery"] = true,
            ["outdoor_seating"] = true,
            ["payment"] = true,
            ["reservation"] = true,
            ["reusable_packaging:offer"] = true,
            ["smoking"] = true,
            ["takeaway"] = true,
            ["television"] = true,
            ["toilets"] = true,
        },
        school = {
            ["capacity"] = true,
            ["denomination"] = true,
            ["operator:type"] = true,
            ["grades"] = true,
            ["language"] = true,
            ["max_age"] = true,
            ["min_age"] = true,
            ["pedagogy"] = true,
            ["religion"] = true,
            ["school"] = true,
            ["school:gender"] = true,
            ["school:language"] = true,
        },
        shelter = {
            ["access"] = true,
            ["bench"] = true,
            ["bin"] = true,
            ["drinking_water"] = true,
            ["floor:material"] = true,
            ["lockable"] = true,
            ["locked"] = true,
            ["picnic_table"] = true,
            ["shelter_type"] = true,
            ["surface"] = true,
            ["table"] = true,
        },
        shower = {
            ["access"] = true,
            ["capacity"] = true,
            ["centralkey"] = true,
            ["charge"] = true,
            ["fee"] = true,
            ["female"] = true,
            ["hot_water"] = true,
            ["indoor"] = true,
            ["male"] = true,
            ["outdoor"] = true,
            ["payment:coins"] = true,
            ["supervised"] = true,
            ["unisex"] = true,
        },
        social_facility = {
            ["social_facility"] = true,
            ["social_facility:for"] = true,
        },
        social_centre = {},
        stripclub = {},
        toilets = {
            ["access"] = true,
            ["charging_table"] = true,
            ["child"] = true,
            ["drinking_water"] = true,
            ["fee"] = true,
            ["female"] = true,
            ["gender_segregated"] = true,
            ["handwashing:creme"] = true,
            ["handwashing:hand_cleaning_paste"] = true,
            ["handwashing:hand_disinfection"] = true,
            ["handwashing:soap"] = true,
            ["hot_water"] = true,
            ["indoor"] = true,
            ["male"] = true,
            ["shower"] = true,
            ["supervised"] = true,
            ["toilets:access"] = true,
            ["toilets:disposal"] = true,
            ["toilets:hands_drying"] = true,
            ["toilets:handwashing"] = true,
            ["toilets:menstrual_products"] = true,
            ["toilets:num_chambers"] = true,
            ["toilets:number"] = true,
            ["toilets:paper_supplied"] = true,
            ["toilets:position"] = true,
            ["unisex"] = true,
        },
        townhall = {
            ["townhall:type"] = true,
        },
        vending_machine = {
            ["coin:type"] = true,
            ["covered"] = true,
            ["currency:USD"] = true,
            ["drink"] = true,
            ["fishing_bait"] = true,
            ["fuel:lpg"] = true,
            ["payment"] = true,
            ["payment:coins:denominations"] = true,
            ["payment:credit_cards"] = true,
            ["payment:notes:denominations"] = true,
            ["reusable_packaging:accept"] = true,
            ["reusable_packaging:offer"] = true,
            ["shop"] = true,
            ["tickets:public_transport"] = true,
            ["vending"] = true,
        },
        waste_transfer_station = {},
        water_point = {},
        weighbridge = {},
    },
    swaps = {
        healthcare = "clinic",
    },
    swaps_to_properties = {
        public_building = { "office", "government" },
        view = { "tourism", "viewpoint" },
    },
}
