return {
    ignored = {},
    properties = {
        block = {
            ["access"] = true,
            ["maxwidth"] = true,
            ["maxwidth:physical"] = true,
            ["motor_vehicle"] = true,
        },
        bollard = {
            ["access"] = true,
            ["bicycle"] = true,
            ["bollard"] = true,
            ["foot"] = true,
            ["horse"] = true,
            ["maxwidth:physical"] = true,
            ["mofa"] = true,
            ["moped"] = true,
        },
        fence = {
            ["fence_type"] = true,
            ["height"] = true,
        },
        gate = {
            ["access"] = true,
            ["bicycle"] = true,
            ["foot"] = true,
            ["height"] = true,
            ["locked"] = true,
            ["maxwidth"] = true,
            ["snowmobile"] = true,
        },
        guard_rail = {},
        hedge = {
            ["genus"] = true,
            ["height"] = true,
            ["leaf_cycle"] = true,
            ["leaf_type"] = true,
            ["species"] = true,
            ["taxon"] = true,
            ["width"] = true,
        },
        kissing_gate = {
            ["centralkey"] = true,
            ["kissing_gate"] = true,
            ["maxwidth"] = true,
        },
        retaining_wall = {
            ["height"] = true,
            ["material"] = true,
        },
        swing_gate = {
            ["access"] = true,
            ["locked"] = true,
            ["material"] = true,
            ["swing_gate:type"] = true,
        },
        toll_booth = {
            ["hov"] = true,
            ["toll"] = true,
            ["toll:bicycle"] = true,
            ["toll:bus"] = true,
            ["toll:hgv"] = true,
            ["toll:hov"] = true,
            ["toll:lanes"] = true,
            ["toll:motorcycle"] = true,
        },
        wall = {
            ["colour"] = true,
            ["height"] = true,
            ["material"] = true,
            ["min_height"] = true,
            ["wall"] = true,
            ["width"] = true,
        },
    },
    swaps = {},
    swaps_to_properties = {},
}
