return {
    ignored = {
        nature_reserve = true,
    },
    properties = {
        garden = {
            ["access"] = true,
            ["garden:style"] = true,
            ["garden:type"] = true,
        },
        golf_course = {
            ["golf"] = true,
            ["golf:course"] = true,
            ["golf:par"] = true,
        },
        ice_rink = {
            ["covered"] = true,
            ["seasonal"] = true,
            ["sport"] = true,
        },
        outdoor_seating = {
            ["access"] = true,
            ["capacity"] = true,
            ["covered"] = true,
            ["heating"] = true,
            ["internet_access"] = true,
            ["lit"] = true,
            ["outdoor_seating"] = true,
            ["outdoor_seating:comfort"] = true,
            ["playground"] = true,
            ["seasonal"] = true,
            ["weather_protection"] = true,
        },
        park = {
            ["access"] = true,
            ["barrier"] = true,
            ["dog"] = true,
        },
        picnic_table = {
            ["access"] = true,
            ["backrest"] = true,
            ["bench"] = true,
            ["colour"] = true,
            ["covered"] = true,
            ["direction"] = true,
            ["lit"] = true,
            ["material"] = true,
            ["smoking"] = true,
        },
        pitch = {
            ["baseball"] = true,
            ["covered"] = true,
            ["hoops"] = true,
            ["indoor"] = true,
            ["level"] = true,
            ["lit"] = true,
            ["sport"] = true,
            ["surface"] = true,
        },
        playground = {
            ["access"] = true,
            ["fee"] = true,
            ["indoor"] = true,
            ["max_age"] = true,
            ["min_age"] = true,
            ["playground"] = true,
            ["playground:theme"] = true,
            ["supervised"] = true,
            ["surface"] = true,
            ["theme"] = true,
        },
        slipway = {
            ["access"] = true,
            ["fee"] = true,
            ["incline"] = true,
            ["slipway"] = true,
            ["surface"] = true,
        },
        sports_centre = {
            ["fee"] = true,
            ["sport"] = true,
        },
        swimming_pool = {
            ["access"] = true,
            ["depth"] = true,
            ["fee"] = true,
            ["heating"] = true,
            ["length"] = true,
            ["lifeguard"] = true,
            ["location"] = true,
            ["maxdepth"] = true,
            ["mindepth"] = true,
            ["nudism"] = true,
            ["ownership"] = true,
            ["salt"] = true,
            ["sport"] = true,
            ["swimming_lanes"] = true,
            ["tidal"] = true,
        },
        track = {
            ["lanes"] = true,
            ["sport"] = true,
            ["surface"] = true,
            ["width"] = true,
        },
    },
    swaps = {},
    swaps_to_properties = {},
}
