return {
    ignored = {},
    properties = {
        bridge = {
            ["bridge:movable"] = true,
            ["bridge:structure"] = true,
            ["bridge:support"] = true,
            ["layer"] = true,
            ["surface"] = true,
        },
        charge_point = {
            ["capacity"] = true,
            ["payment:contactless"] = true,
        },
        cooling = {
            ["cooling:method"] = true,
        },
        cutline = {
            ["cutline"] = true,
            ["width"] = true,
        },
        dyke = {},
        mast = {
            ["communication:bos"] = true,
            ["communication:microwave"] = true,
            ["communication:mobile_phone"] = true,
            ["height"] = true,
            ["mast:type"] = true,
            ["mimics"] = true,
            ["tower:construction"] = true,
            ["tower:type"] = true,
        },
        pier = {
            ["access"] = true,
            ["floating"] = true,
            ["mooring"] = true,
            ["public_transport"] = true,
        },
        pipeline = {
            ["count"] = true,
            ["diameter"] = true,
            ["flow_direction"] = true,
            ["layer"] = true,
            ["location"] = true,
            ["place:destination"] = true,
            ["place:origin"] = true,
            ["pressure"] = true,
            ["substance"] = true,
            ["usage"] = true,
        },
        pumping_station = {
            ["disused"] = true,
            ["pipeline"] = true,
            ["pumping_station"] = true,
            ["substance"] = true,
            ["utility"] = true,
        },
        silo = {
            ["building:material"] = true,
            ["content"] = true,
            ["crop"] = true,
            ["height"] = true,
        },
        storage_tank = {
            ["capacity"] = true,
            ["content"] = true,
            ["height"] = true,
            ["location"] = true,
            ["material"] = true,
        },
        tower = {
            ["access"] = true,
            ["ele"] = true,
            ["height"] = true,
            ["material"] = true,
            ["mimics"] = true,
            ["service"] = true,
            ["source"] = true,
            ["tower:construction"] = true,
            ["tower:insulated"] = true,
            ["tower:type"] = true,
            ["viewpoint"] = true,
        },
        wastewater_plant = {},
        water_tower = {
            ["access"] = true,
            ["capacity"] = true,
            ["disused"] = true,
            ["height"] = true,
            ["historic"] = true,
        },
        water_works = {
            ["water_works"] = true,
        },
        works = {
            ["product"] = true,
        },
    },
    swaps = {},
    swaps_to_properties = {},
}
