return {
    ignored = {
        yes = true,
    },
    properties = {
        arete = {},
        bare_rock = {},
        bay = {},
        beach = {
            ["emergency"] = true,
            ["fee"] = true,
            ["lifeguard"] = true,
            ["supervised"] = true,
            ["surface"] = true,
        },
        cape = {},
        cave_entrance ={
            ["access"] = true,
            ["alt_name"] = true,
            ["barrier"] = true,
            ["direction"] = true,
            ["fee"] = true,
            ["material"] = true,
        },
        cliff = {
            ["height"] = true,
            ["surface"] = true,
        },
        grassland = {
            ["grassland"] = true,
            ["species"] = true,
        },
        peak = {
            ["ele"] = true,
            ["summit:cross"] = true,
            ["summit:register"] = true,
        },
        reef = {
            ["reef"] = true,
        },
        ridge = {},
        rock = {},
        sand = {
            ["tidal"] = true,
        },
        scree = {},
        scrub = {
            ["leaf_cycle"] = true,
            ["leaf_type"] = true,
        },
        spring = {
            ["drinking_water"] = true,
            ["drinking_water:legal"] = true,
            ["seasonal"] = true,
            ["water_characteristic"] = true,
        },
        strait = {},
        tree = {
            ["denotation"] = true,
            ["diameter"] = true,
            ["diameter:range"] = true,
            ["diameter_crown"] = true,
            ["est_height"] = true,
            ["genus"] = true,
            ["height"] = true,
            ["height:range"] = true,
            ["leaf_cycle"] = true,
            ["leaf_type"] = true,
            ["planted_date"] = true,
            ["sex"] = true,
            ["species"] = true,
            ["taxon"] = true,
        },
        tree_row = {
            ["height"] = true,
            ["leaf_cycle"] = true,
            ["leaf_type"] = true,
        },
        water = {
            ["intermittent"] = true,
            ["salt"] = true,
            ["water"] = true,
        },
        wetland = {
            ["managed"] = true,
            ["seasonal"] = true,
            ["tidal"] = true,
            ["wetland"] = true,
        },
        wood = {
            ["leaf_cycle"] = true,
            ["leaf_type"] = true,
            ["managed"] = true,
            ["species"] = true,
            ["taxon"] = true,
        },
    },
    swaps = {},
    swaps_to_properties = {},
}
