return {
    ignored = {
        archipelago = true,
        city_block = true,
        continent = true,
        country = true,
        county = true,
        district = true,
        municipality = true,
        ocean = true,
        plot = true,
        polder = true,
        province = true,
        region = true,
        sea = true,
        square = true,
        state = true,
        subdistrict = true,
    },
    properties = {
        allotments = {},
        borough = {},
        city = {},
        farm = {},
        hamlet = {},
        island = {},
        islet = {},
        isolated_dwelling = {},
        locality = {},
        neighbourhood = {},
        quarter = {},
        suburb = {},
        town = {},
        village = {},
    },
    swaps = {},
    swaps_to_properties = {},
}
