return {
    ignored = {},
    properties = {
        generator = {
            ["generator:method"] = true,
            ["generator:output:biogas"] = true,
            ["generator:output:cold_air"] = true,
            ["generator:output:cold_water"] = true,
            ["generator:output:compressed_air"] = true,
            ["generator:output:electricity"] = true,
            ["generator:output:heat"] = true,
            ["generator:output:hot_air"] = true,
            ["generator:output:hot_water"] = true,
            ["generator:output:hydrogen"] = true,
            ["generator:output:steam"] = true,
            ["generator:output:vacuum"] = true,
            ["generator:plant"] = true,
            ["generator:source"] = true,
            ["generator:type"] = true,
            ["height"] = true,
            ["height:hub"] = true,
            ["model"] = true,
            ["rotor:diameter"] = true,
        },
        line = {
            ["cables"] = true,
            ["circuits"] = true,
            ["line"] = true,
            ["voltage"] = true,
            ["wires"] = true,
        },
        minor_line = {
            ["cables"] = true,
            ["circuits"] = true,
            ["voltage"] = true,
            ["wires"] = true,
        },
        plant = {
            ["plant:method"] = true,
            ["plant:output:biogas"] = true,
            ["plant:output:cold_air"] = true,
            ["plant:output:cold_water"] = true,
            ["plant:output:compressed_air"] = true,
            ["plant:output:electricity"] = true,
            ["plant:output:hot_air"] = true,
            ["plant:output:hot_water"] = true,
            ["plant:output:steam"] = true,
            ["plant:output:vacuum"] = true,
            ["plant:source"] = true,
            ["plant:storage"] = true,
        },
        pole = {
            ["design"] = true,
            ["height"] = true,
            ["highway"] = true,
            ["line_arrangement"] = true,
            ["line_attachment"] = true,
            ["line_management"] = true,
            ["material"] = true,
            ["phases:primary"] = true,
            ["phases:secondary"] = true,
            ["structure"] = true,
            ["transformer"] = true,
            ["voltage:primary"] = true,
            ["voltage:secondary"] = true,
        },
        substation = {
            ["gas_insulated"] = true,
            ["location"] = true,
            ["substation"] = true,
            ["voltage"] = true,
        },
        tower = {
            ["colour"] = true,
            ["design"] = true,
            ["height"] = true,
            ["line_arrangement"] = true,
            ["line_attachment"] = true,
            ["line_management"] = true,
            ["location:transition"] = true,
            ["material"] = true,
            ["structure"] = true,
        },
    },
    swaps = {},
    swaps_to_properties = {},
}
