return {
    ignored = {},
    properties = {
        abandoned = {
            ["cutting"] = true,
            ["embankment"] = true,
            ["embankment:side"] = true,
            ["embankment:type"] = true,
        },
        crossing = {
            ["crossing"] = true,
            ["crossing:activation"] = true,
            ["crossing:barrier"] = true,
            ["crossing:bell"] = true,
            ["crossing:light"] = true,
            ["crossing:on_demand"] = true,
            ["crossing:saltire"] = true,
        },
        disused = {
            ["cutting"] = true,
            ["embankment"] = true,
            ["embankment:side"] = true,
            ["embankment:type"] = true,
        },
        junction = {},
        level_crossing = {
            ["crossing"] = true,
            ["crossing:activation"] = true,
            ["crossing:barrier"] = true,
            ["crossing:bell"] = true,
            ["crossing:light"] = true,
            ["crossing:on_demand"] = true,
            ["crossing:saltire"] = true,
            ["crossing:uncontrolled"] = true,
            ["crossing:whistle"] = true,
        },
        milestone = {
            ["railway:position"] = true,
        },
        rail = {
            ["bridge"] = true,
            ["cutting"] = true,
            ["electrified"] = true,
            ["embankment"] = true,
            ["embankment:side"] = true,
            ["embankment:type"] = true,
            ["gauge"] = true,
            ["voltage"] = true,
            ["rack"] = true,
            ["tunnel"] = true,
            ["usage"] = true,
            ["service"] = true,
            ["tracks"] = true,
        },
        roundhouse = {
            ["length"] = true,
        },
        switch = {
            ["railway:local_operated"] = true,
            ["railway:switch"] = true,
            ["railway:switch:configuration"] = true,
            ["railway:switch:electric"] = true,
            ["railway:switch:frog"] = true,
            ["railway:switch:heated"] = true,
            ["railway:switch:movable_frog"] = true,
            ["railway:switch:resetting"] = true,
            ["railway:turnout_side"] = true,
        },
        turntable = {
            ["electrified"] = true,
            ["gauge"] = true,
            ["rack"] = true,
            ["service"] = true,
            ["voltage"] = true,
        },
    },
    swaps = {},
    swaps_to_properties = {},
}
