return {
    ignored = {},
    properties = {
        art = {
            ["training"] = true,
        },
        bakery = {
            ["bakehouse"] = true,
            ["diet:gluten_free"] = true,
            ["diet:lactose_free"] = true,
            ["diet:vegan"] = true,
            ["ice_cream"] = true,
            ["organic"] = true,
            ["oven"] = true,
            ["pastry"] = true,
            ["pastry_shop"] = true,
            ["payment"] = true,
            ["reusable_packaging:accept"] = true,
            ["reusable_packaging:offer"] = true,
        },
        books = {
            ["books"] = true,
            ["second_hand"] = true,
            ["payment"] = true,
        },
        cannabis = {
            ["cannabis:cbd"] = true,
            ["cannabis:medical"] = true,
            ["cannabis:recreational"] = true,
            ["cannabis:seeds"] = true,
        },
        car = {
            ["payment"] = true,
            ["second_hand"] = true,
            ["service"] = true,
            ["service:vehicle:car_parts"] = true,
            ["service:vehicle:car_repair"] = true,
            ["service:vehicle:electrical"] = true,
            ["service:vehicle:glass"] = true,
            ["service:vehicle:inspection"] = true,
            ["service:vehicle:new_car_sales"] = true,
            ["service:vehicle:truck_repair"] = true,
            ["service:vehicle:tyres"] = true,
        },
        car_parts = {
            ["payment"] = true,
            ["second_hand"] = true,
            ["service:vehicle:type"] = true,
            ["service:vehicle:tyres"] = true,
        },
        car_repair = {
            ["service:vehicle:car_parts"] = true,
            ["service:vehicle:car_repair"] = true,
            ["service:vehicle:inspection"] = true,
            ["service:vehicle:oil_change"] = true,
            ["service:vehicle:tyres"] = true,
        },
        charity = {
            ["second_hand"] = true,
        },
        chemist = {
            ["clothes"] = true,
            ["medical_supply"] = true,
        },
        clothes = {
            ["clothes"] = true,
            ["organic"] = true,
            ["second_hand"] = true,
        },
        coffee = {
            ["organic"] = true,
        },
        convenience = {
            ["ice_cream"] = true,
            ["ice_cream:type"] = true,
            ["fair_trade"] = true,
            ["organic"] = true,
            ["origin"] = true,
            ["payment"] = true,
            ["reusable_packaging:accept"] = true,
            ["reusable_packaging:offer"] = true,
        },
        country_store = {},
        department_store = {
            ["payment"] = true,
        },
        doityourself = {},
        farm = {
            ["delivery"] = true,
            ["organic"] = true,
            ["payment"] = true,
            ["produce"] = true,
            ["product"] = true,
        },
        florist = {
            ["delivery"] = true,
        },
        funeral_directors = {
            ["denomination"] = true,
            ["religion"] = true,
        },
        garden_centre = {},
        gift = {
            ["gift"] = true,
        },
        hairdresser = {
            ["beauty"] = true,
            ["female"] = true,
            ["hairdresser"] = true,
            ["male"] = true,
            ["reservation"] = true,
        },
        hardware = {},
        laundry = {
            ["dry_cleaning"] = true,
            ["laundry_service"] = true,
            ["payment"] = true,
            ["self_service"] = true,
        },
        -- market = {},
        motorcycle = {
            ["clothes"] = true,
            ["motorcycle"] = true,
            ["motorcycle:clothes"] = true,
            ["motorcycle:parts"] = true,
            ["motorcycle:rental"] = true,
            ["motorcycle:repair"] = true,
            ["motorcycle:sales"] = true,
            ["motorcycle:type"] = true,
            ["parts"] = true,
            ["rental"] = true,
            ["repair"] = true,
            ["sales"] = true,
            ["second_hand"] = true,
        },
        rental = {
            ["rental"] = true,
        },
        snowmobile = {},
        sports = {
            ["clothes"] = true,
            ["payment"] = true,
            ["sport"] = true,
        },
        storage_rental = {},
        supermarket = {
            ["bulk_purchase"] = true,
            ["fair_trade"] = true,
            ["membership"] = true,
            ["organic"] = true,
            ["origin"] = true,
            ["payment"] = true,
            ["reusable_packaging:accept"] = true,
            ["reusable_packaging:offer"] = true,
        },
        taxidermy = {},
        variety_store = {},
        yes = {},
    },
    swaps = {},
    swaps_to_properties = {
        market = { "amenity", "marketplace" },
    },
}
