return {
    ignored = {},
    properties = {
        camp_pitch = {
            ["capacity"] = true,
            ["caravans"] = true,
            ["drinking_water"] = true,
            ["fireplace"] = true,
            ["internet_access"] = true,
            ["openfire"] = true,
            ["parking"] = true,
            ["permanent_camping"] = true,
            ["picnic_table"] = true,
            ["power_supply"] = true,
            ["surface"] = true,
            ["tents"] = true,
        },
        camp_site = {
            ["backcountry"] = true,
            ["bbq"] = true,
            ["cabins"] = true,
            ["camp_site"] = true,
            ["capacity:cabins"] = true,
            ["capacity:caravans"] = true,
            ["capacity:persons"] = true,
            ["capacity:pitches"] = true,
            ["capacity:tents"] = true,
            ["caravans"] = true,
            ["dog"] = true,
            ["drinking_water"] = true,
            ["fee"] = true,
            ["group_only"] = true,
            ["hot_water"] = true,
            ["impromptu"] = true,
            ["internet_access"] = true,
            ["kitchen"] = true,
            ["lit"] = true,
            ["motor_vehicle"] = true,
            ["motorhome"] = true,
            ["nudism"] = true,
            ["openfire"] = true,
            ["permanent_camping"] = true,
            ["picnic_table"] = true,
            ["power_supply"] = true,
            ["reservation"] = true,
            ["sanitary_dump_station"] = true,
            ["scout"] = true,
            ["shower"] = true,
            ["smoking"] = true,
            ["stars"] = true,
            ["static_caravans"] = true,
            ["swimming_pool"] = true,
            ["tents"] = true,
            ["toilets"] = true,
            ["washing_machine"] = true,
            ["waste_disposal"] = true,
        },
        chalet = {
            ["dog"] = true,
            ["horse"] = true,
            ["internet_access"] = true,
            ["pets"] = true,
            ["pets_allowed"] = true,
        },
        gallery = {
            ["artwork_type"] = true,
            ["fee"] = true,
        },
        guest_house = {
            ["beds"] = true,
            ["guest_house"] = true,
            ["internet_access"] = true,
            ["payment"] = true,
            ["rooms"] = true,
            ["smoking"] = true,
        },
        hotel = {
            ["bar"] = true,
            ["beds"] = true,
            ["internet_access"] = true,
            ["payment:american_express"] = true,
            ["payment:cash"] = true,
            ["payment:cheque"] = true,
            ["payment:discover_card"] = true,
            ["payment:mastercard"] = true,
            ["rooms"] = true,
            ["service:bicycle:rental"] = true,
            ["smoking"] = true,
            ["stars"] = true,
            ["swiming_pool"] = true,
        },
        information = {
            ["board_type"] = true,
            ["information"] = true,
            ["map_size"] = true,
            ["map_type"] = true,
        },
        motel = {
            ["beds"] = true,
            ["rooms"] = true,
            ["smoking"] = true,
        },
        museum = {
            ["museum"] = true,
            ["museum_type"] = true,
            ["operator:type"] = true,
            ["payment"] = true,
            ["subject"] = true,
        },
        picnic_site = {
            ["bbq"] = true,
            ["covered"] = true,
            ["drinking_water"] = true,
            ["fireplace"] = true,
            ["openfire"] = true,
        },
        -- sporting_camp = {},
        viewpoint = {
            ["direction"] = true,
        },
        wilderness_hut = {
            ["access"] = true,
            ["capacity"] = true,
            ["drinking_water"] = true,
            ["fee"] = true,
            ["fireplace"] = true,
            ["locked"] = true,
            ["mattress"] = true,
            ["reservation"] = true,
            ["shower"] = true,
            ["toilets"] = true,
        },
    },
    swaps = {
        sporting_camp = "camp_site",
    },
    swaps_to_properties = {},
}
